services:
  web:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-master
    environment:
      DOCKER_HOST: tcp://docker:2376 
      DOCKER_CERT_PATH: certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./volumes/jenkins-master:/var/jenkins_home:rw
      # - ./volumes/jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins-network

  jenkins_slave:
    image: jenkins/slave:4.13.3-2-alpine
    container_name: jnlp_slave
    # command: -url http://jenkins-master:8080 $JENKINS_SECRET $JENKINS_AGENT_NAME
    # restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./volumes/jnlp_slave:/var/jenkins_home
    environment:
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_SECRET: ${JENKINS_SECRET}
      JENKINS_AGENT_NAME: ${JENKINS_AGENT_NAME}
    env_file:
      - .env
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
    name: jenkins-network