services:
  jenkins-master:
    image: jenkins/jenkins:alpine3.21-jdk21
    container_name: jenkins-master
    volumes:
      # Removed /var/run/docker.sock and /usr/bin/docker
      - ./volumes/jenkins-master:/var/jenkins_home:rw
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins-network

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent
    volumes:
      - ./volumes/inbound-agent:/var/jenkins_home
    environment:
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_SECRET: ${JENKINS_SECRET}
      JENKINS_AGENT_NAME: ${JENKINS_AGENT_NAME}
    env_file:
      - .env
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
    name: jenkins-network


# curl -sO http://172.18.0.1:8080/jnlpJars/agent.jar
# java -jar agent.jar -url http://172.18.0.1:8080/ -secret c3aa266dd274d7b33756be3b2c23ffd9cdff099190c9c2f34aee299a2c28e445 -name "jenkins-inbound-agent-1" -webSocket -workDir "/home/jenkins"